services:
  # === База данных ===
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: always

  # === Redis (Брокер для Celery и Channels) ===
  redis:
    image: redis:7-alpine
    restart: always

  # === Backend (Django + Daphne) ===
  backend:
    build: ./backend
    # Запускаем через daphne для поддержки WebSocket
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application
    volumes:
      - static_volume:/app/staticfiles  # Сюда collectstatic сложит файлы
      - media_volume:/app/media         # Сюда загружаются файлы
    expose:
      - "8000" # Порт доступен только внутри сети Docker (для Nginx)
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432
      - REDIS_HOST=redis
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=False
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend,193.180.213.143,careyour.pet,www.careyour.pet
      - DATABASE=postgres
      # CORS настройки
      - CORS_ALLOWED_ORIGINS=https://careyour.pet,https://www.careyour.pet,http://localhost:3000
      - CSRF_TRUSTED_ORIGINS=https://careyour.pet,https://www.careyour.pet,http://localhost:3000
    depends_on:
      - db
      - redis
    restart: always

  # === Frontend (Next.js) ===
  frontend:
    build: ./frontend
    expose:
      - "3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://careyour.pet
    depends_on:
      - backend
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  # === Nginx (Прокси) ===
  nginx:
    image: nginx:1.27-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/backend/staticfiles:ro # Читаем статику Django
      - media_volume:/app/backend/media:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot      # Читаем медиа Django
    depends_on:
      - backend
      - frontend
    restart: always

  # === Celery Worker (Задачи) ===
  celery_worker:
    build: ./backend
    command: celery -A config worker -l info
    volumes:
      - media_volume:/app/media
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE=postgres
    depends_on:
      - db
      - redis
      - backend
    restart: always

  # === Celery Beat (Планировщик) ===
  celery_beat:
    build: ./backend
    command: celery -A config beat -l info
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE=postgres
    depends_on:
      - db
      - redis
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume: